/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-14 05:09:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- External stylesheet link -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/about.css\">\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Logo and Brand Name -->\r\n");
      out.write("	<img src=\"images\\logo.png\" class=\"logo\">\r\n");
      out.write("\r\n");
      out.write("	<h1 class=\"logo_topic\">FreshCraze</h1>\r\n");
      out.write("\r\n");
      out.write("	<!-- Navigation Bar -->\r\n");
      out.write("	<nav class=\"navbar\">\r\n");
      out.write("		<a href=\"index.jsp\">Home</a> <a href=\"register.jsp\">Sign Up</a> <a\r\n");
      out.write("			href=\"mainLogin.jsp\">Sign In</a> <a href=\"item.jsp\">Product</a> <a\r\n");
      out.write("			href=\"about.jsp\">About Us</a> <a href=\"mainLogin.jsp\">FAQs</a> <span></span>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<hr class=\"topic_line\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Main Content Section -->\r\n");
      out.write("	<div class=\"content\">\r\n");
      out.write("		<h1>Our Services.....</h1>\r\n");
      out.write("		<!-- Description -->\r\n");
      out.write("		<p>Welcome to FreshCraze, your one-stop destination for all your\r\n");
      out.write("			grocery needs. At FreshCraze, we're passionate about providing fresh,\r\n");
      out.write("			high-quality groceries at affordable prices, delivered straight to\r\n");
      out.write("			your doorstep.</p>\r\n");
      out.write("		<p>Our mission is to make grocery shopping convenient and\r\n");
      out.write("			enjoyable for our customers. Whether you're looking for fresh fruits\r\n");
      out.write("			and vegetables, pantry staples, or specialty items, we've got you\r\n");
      out.write("			covered.</p>\r\n");
      out.write("		<p>With our easy-to-use online ordering system, you can browse our\r\n");
      out.write("			wide selection of products, place orders from the comfort of your\r\n");
      out.write("			home, and have them delivered at a time that suits you best.</p>\r\n");
      out.write("		<p>Customer satisfaction is our top priority, and we strive to\r\n");
      out.write("			exceed your expectations with every order. Our dedicated team works\r\n");
      out.write("			tirelessly to ensure that your groceries are carefully selected,\r\n");
      out.write("			packed, and delivered with the utmost care.</p>\r\n");
      out.write("		<p>Thank you for choosing FreshCraze for your grocery needs. We\r\n");
      out.write("			look forward to serving you and providing you with a fresh and\r\n");
      out.write("			delightful shopping experience!</p>\r\n");
      out.write("\r\n");
      out.write("		<!-- Team Section -->\r\n");
      out.write("		<h2>Our Team</h2>\r\n");
      out.write("		<p>Meet the team behind FreshCraze:</p>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li>AMBEGODA A L A S K</li>\r\n");
      out.write("			<li>SILVA K S S G</li>\r\n");
      out.write("			<li>WANASINGHE W A H N</li>\r\n");
      out.write("			<li>PERERA L C C</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<hr class=\"footer_line\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer Section -->\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<a href=\"link\" target=\"_blank\">\r\n");
      out.write("			<button type=\"button\" class=\"help_button\">Help and Support</button>\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"fb_icon\">\r\n");
      out.write("			<a href=\"https://www.facebook.com/\" target=\"_blank\"><img\r\n");
      out.write("				src=\"images/facebook.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"insta_icon\">\r\n");
      out.write("			<a href=\"https://www.instagram.com/\" target=\"_blank\"><img\r\n");
      out.write("				src=\"images/insta.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"twitt_icon\">\r\n");
      out.write("			<a href=\"https://www.twitter.com/\" target=\"_blank\"><img\r\n");
      out.write("				src=\"images/Twitter.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"yt_icon\">\r\n");
      out.write("			<a href=\"https://www.youtube.com/\" target=\"_blank\"><img\r\n");
      out.write("				src=\"images/yt.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Contact Information -->\r\n");
      out.write("	<div class=\"contacts\">\r\n");
      out.write("		<h1 class=\"link\">www.freshcraze.lk</h1>\r\n");
      out.write("		<h1>Hotline: +94 225 225 25 / +94 225 225 35</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
