/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-16 13:16:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class updateItem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Link to the updateItem.css stylesheet -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/updateItem.css\">\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- FreshCraze logo and topic -->\r\n");
      out.write("	<img src=\"images\\logo.png\" class=\"logo\">\r\n");
      out.write("\r\n");
      out.write("	<h1 class=\"logo_topic\">FreshCraze</h1>\r\n");
      out.write("\r\n");
      out.write("	<!-- Navigation bar -->\r\n");
      out.write("	<nav class=\"navbar\">\r\n");
      out.write("		<a href=\"index.jsp\">Home</a> <a href=\"register.jsp\">Sign Up</a> <a\r\n");
      out.write("			href=\"mainLogin.jsp\">Sign In</a> <a href=\"item.jsp\">Product</a> <a\r\n");
      out.write("			href=\"about.jsp\">About Us</a> <a href=\"mainLogin.jsp\">FAQs</a> <span></span>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<hr class=\"topic_line\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Container for the form to add item -->\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h2>Add Item</h2>\r\n");
      out.write("\r\n");
      out.write("		<!-- Form to add item, action set to \"updateItem\" -->\r\n");
      out.write("		<form action=\"updateItem\" method=\"post\"\r\n");
      out.write("			onsubmit=\"return validateForm()\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Input fields for item details -->\r\n");
      out.write("			<label for=\"item_code\">Item Code:</label><br> <input type=\"text\"\r\n");
      out.write("				id=\"item_code\" name=\"itemCode\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.itemCode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br>\r\n");
      out.write("			<br> <label for=\"item_name\">Item Name:</label><br> <input\r\n");
      out.write("				type=\"text\" id=\"item_name\" name=\"itemName\" required\r\n");
      out.write("				value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.itemName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br> <br> <label\r\n");
      out.write("				for=\"category\">Category:</label><br> <select id=\"category\"\r\n");
      out.write("				name=\"category\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<option value=\"Beverages\">Beverages</option>\r\n");
      out.write("				<option value=\"Choco & Snacks\">Choco and Snacks</option>\r\n");
      out.write("				<option value=\"Food-Staples\">Food-Staples</option>\r\n");
      out.write("				<option value=\"Laundry & Household\">Laundry and Household</option>\r\n");
      out.write("\r\n");
      out.write("			</select><br> <br> <label for=\"quantity\">Quantity:</label><br>\r\n");
      out.write("			<input type=\"number\" id=\"quantity\" name=\"quantity\" min=\"0\" required\r\n");
      out.write("				value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br> <br> <label\r\n");
      out.write("				for=\"price\">Price:</label><br> <input type=\"text\" id=\"price\"\r\n");
      out.write("				name=\"price\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br> <br>\r\n");
      out.write("			<label for=\"description\">Description:</label><br> <input\r\n");
      out.write("				type=\"text\" id=\"description\" name=\"description\" required\r\n");
      out.write("				value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.description }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><br> <br> <input\r\n");
      out.write("				type=\"submit\" value=\"Add Item\">\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		function validateForm() {\r\n");
      out.write("			var itemCode = document.getElementById(\"item_code\").value;\r\n");
      out.write("			var itemName = document.getElementById(\"item_name\").value;\r\n");
      out.write("			var category = document.getElementById(\"category\").value;\r\n");
      out.write("			var quantity = document.getElementById(\"quantity\").value;\r\n");
      out.write("			var price = document.getElementById(\"price\").value;\r\n");
      out.write("			var description = document.getElementById(\"description\").value;\r\n");
      out.write("\r\n");
      out.write("			// Check if any field is empty\r\n");
      out.write("			if (itemCode == \"\" || itemName == \"\" || category == \"\"\r\n");
      out.write("					|| quantity == \"\" || price == \"\" || description == \"\") {\r\n");
      out.write("				alert(\"All fields must be filled out\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			if (/\\d/.test(itemName)) {\r\n");
      out.write("				alert(\"Item name cannot contain numbers\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// Check if price is a valid number\r\n");
      out.write("			if (!/^\\d+(\\.\\d+)?$/.test(price) || parseFloat(price) <= 0) {\r\n");
      out.write("				alert(\"Price must be a valid positive number greater than 0\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			// Check if quantity is a valid number\r\n");
      out.write("			if (!/^[1-9]\\d*$/.test(quantity)) {\r\n");
      out.write("				alert(\"Quantity must be a valid positive integer or greater than 0\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			return true;\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<hr class=\"footer_line\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer section -->\r\n");
      out.write("	<div class=\"footer\">\r\n");
      out.write("		<a href=\"link\" target=\"_blank\">\r\n");
      out.write("			<button type=\"button\" class=\"help_button\">Help and Support</button>\r\n");
      out.write("		</a>\r\n");
      out.write("\r\n");
      out.write("		<!-- Social media icons -->\r\n");
      out.write("		<div class=\"fb_icon\">\r\n");
      out.write("			<a href=\"https://www.facebook.com/\" target=\"_blank\"><img\r\n");
      out.write("				src=\"images/facebook.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"insta_icon\">\r\n");
      out.write("			<a href=\"https://www.instagram.com/\" target=\"_blank\"><img\r\n");
      out.write("				src=\"images/insta.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"twitt_icon\">\r\n");
      out.write("			<a href=\"https://www.twitter.com/\" target=\"_blank\"><img\r\n");
      out.write("				src=\"images/Twitter.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"yt_icon\">\r\n");
      out.write("			<a href=\"https://www.youtube.com/\" target=\"_blank\"><img\r\n");
      out.write("				src=\"images/yt.png\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Contact information -->\r\n");
      out.write("	<div class=\"contacts\">\r\n");
      out.write("		<h1 class=\"link\">www.freshcraze.lk</h1>\r\n");
      out.write("		<h1>Hotline: +94 225 225 25 / +94 225 225 35</h1>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
